# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the bdsg/docs/ directory with Sphinx
sphinx:
  configuration: bdsg/docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: bdsg/docs/requirements.txt

build:
  os: ubuntu-22.04
  apt_packages:
    - libjansson-dev

submodules:
  include: all
  recursive: true
