# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set OS and Python version
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - libjansson-dev
    - cmake

# Build documentation in the bdsg/docs/ directory with Sphinx
sphinx:
  configuration: bdsg/docs/conf.py


# Install requirements into Python
python:
  install:
    - requirements: bdsg/docs/requirements.txt

submodules:
  include: all
  recursive: true
