#include <bdsg/internal/base_packed_graph.hpp>
#include <bdsg/internal/mapped_structs.hpp>
#include <functional>
#include <handlegraph/types.hpp>
#include <ios>
#include <istream>
#include <iterator>
#include <memory>
#include <ostream>
#include <sstream> // __str__
#include <streambuf>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <functional>
#include <pybind11/pybind11.h>
#include <string>
#include <bdsg/internal/binder_hook_compile.hpp>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <pybind11/functional.h>
#include <fstream>


#ifndef BINDER_PYBIND11_TYPE_CASTER
	#define BINDER_PYBIND11_TYPE_CASTER
	PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>)
	PYBIND11_DECLARE_HOLDER_TYPE(T, T*)
	PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>)
#endif

void bind_bdsg_internal_base_packed_graph(std::function< pybind11::module &(std::string const &namespace_) > &M)
{
	{ // bdsg::BasePackedGraph file:bdsg/internal/base_packed_graph.hpp line:53
		pybind11::class_<bdsg::BasePackedGraph<bdsg::STLBackend>, std::shared_ptr<bdsg::BasePackedGraph<bdsg::STLBackend>>> cl(M("bdsg"), "BasePackedGraph_bdsg_STLBackend_t", "");
		cl.def( pybind11::init( [](){ return new bdsg::BasePackedGraph<bdsg::STLBackend>(); } ) );
		cl.def( pybind11::init( [](bdsg::BasePackedGraph<bdsg::STLBackend> const &o){ return new bdsg::BasePackedGraph<bdsg::STLBackend>(o); } ) );
		cl.def("has_node", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(long long) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::has_node, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::has_node(long long) const --> bool", pybind11::arg("node_id"));
		cl.def("get_handle", [](bdsg::BasePackedGraph<bdsg::STLBackend> const &o, const long long & a0) -> handlegraph::handle_t { return o.get_handle(a0); }, "", pybind11::arg("node_id"));
		cl.def("get_handle", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const long long &, bool) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_handle(const long long &, bool) const --> struct handlegraph::handle_t", pybind11::arg("node_id"), pybind11::arg("is_reverse"));
		cl.def("get_id", (long long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_id, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_id(const struct handlegraph::handle_t &) const --> long long", pybind11::arg("handle"));
		cl.def("get_is_reverse", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_is_reverse, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_is_reverse(const struct handlegraph::handle_t &) const --> bool", pybind11::arg("handle"));
		cl.def("flip", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::flip, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::flip(const struct handlegraph::handle_t &) const --> struct handlegraph::handle_t", pybind11::arg("handle"));
		cl.def("get_length", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_length, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_length(const struct handlegraph::handle_t &) const --> unsigned long", pybind11::arg("handle"));
		cl.def("get_sequence", (std::string (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_sequence, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_sequence(const struct handlegraph::handle_t &) const --> std::string", pybind11::arg("handle"));
		cl.def("follow_edges", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, bool, const class std::function<bool (const struct handlegraph::handle_t &)> &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::follow_edges, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::follow_edges(const struct handlegraph::handle_t &, bool, const class std::function<bool (const struct handlegraph::handle_t &)> &) const --> bool", pybind11::arg("handle"), pybind11::arg("go_left"), pybind11::arg("iteratee"));
		cl.def("for_each_handle", [](bdsg::BasePackedGraph<bdsg::STLBackend> const &o, const class std::function<bool (const struct handlegraph::handle_t &)> & a0) -> bool { return o.for_each_handle(a0); }, "", pybind11::arg("iteratee"));
		cl.def("for_each_handle", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const class std::function<bool (const struct handlegraph::handle_t &)> &, bool) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_handle(const class std::function<bool (const struct handlegraph::handle_t &)> &, bool) const --> bool", pybind11::arg("iteratee"), pybind11::arg("parallel"));
		cl.def("get_edge_count", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)() const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_edge_count, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_edge_count() const --> unsigned long");
		cl.def("get_total_length", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)() const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_total_length, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_total_length() const --> unsigned long");
		cl.def("get_base", (char (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, unsigned long) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_base, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_base(const struct handlegraph::handle_t &, unsigned long) const --> char", pybind11::arg("handle"), pybind11::arg("index"));
		cl.def("get_subsequence", (std::string (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, unsigned long, unsigned long) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_subsequence, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_subsequence(const struct handlegraph::handle_t &, unsigned long, unsigned long) const --> std::string", pybind11::arg("handle"), pybind11::arg("index"), pybind11::arg("size"));
		cl.def("forward", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::forward, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::forward(const struct handlegraph::handle_t &) const --> struct handlegraph::handle_t", pybind11::arg("handle"));
		cl.def("get_node_count", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)() const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_node_count, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_node_count() const --> unsigned long");
		cl.def("min_node_id", (long long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)() const) &bdsg::BasePackedGraph<bdsg::STLBackend>::min_node_id, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::min_node_id() const --> long long");
		cl.def("max_node_id", (long long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)() const) &bdsg::BasePackedGraph<bdsg::STLBackend>::max_node_id, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::max_node_id() const --> long long");
		cl.def("get_degree", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, bool) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_degree, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_degree(const struct handlegraph::handle_t &, bool) const --> unsigned long", pybind11::arg("handle"), pybind11::arg("go_left"));
		cl.def("has_edge", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, const struct handlegraph::handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::has_edge, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::has_edge(const struct handlegraph::handle_t &, const struct handlegraph::handle_t &) const --> bool", pybind11::arg("left"), pybind11::arg("right"));
		cl.def("create_handle", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const std::string &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::create_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::create_handle(const std::string &) --> struct handlegraph::handle_t", pybind11::arg("sequence"));
		cl.def("create_handle", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const std::string &, const long long &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::create_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::create_handle(const std::string &, const long long &) --> struct handlegraph::handle_t", pybind11::arg("sequence"), pybind11::arg("id"));
		cl.def("destroy_handle", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::destroy_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::destroy_handle(const struct handlegraph::handle_t &) --> void", pybind11::arg("handle"));
		cl.def("change_sequence", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, const std::string &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::change_sequence, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::change_sequence(const struct handlegraph::handle_t &, const std::string &) --> struct handlegraph::handle_t", pybind11::arg("handle"), pybind11::arg("sequence"));
		cl.def("truncate_handle", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, bool, unsigned long)) &bdsg::BasePackedGraph<bdsg::STLBackend>::truncate_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::truncate_handle(const struct handlegraph::handle_t &, bool, unsigned long) --> struct handlegraph::handle_t", pybind11::arg("handle"), pybind11::arg("trunc_left"), pybind11::arg("offset"));
		cl.def("create_edge", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, const struct handlegraph::handle_t &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::create_edge, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::create_edge(const struct handlegraph::handle_t &, const struct handlegraph::handle_t &) --> void", pybind11::arg("left"), pybind11::arg("right"));
		cl.def("destroy_edge", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, const struct handlegraph::handle_t &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::destroy_edge, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::destroy_edge(const struct handlegraph::handle_t &, const struct handlegraph::handle_t &) --> void", pybind11::arg("left"), pybind11::arg("right"));
		cl.def("clear", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)()) &bdsg::BasePackedGraph<bdsg::STLBackend>::clear, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::clear() --> void");
		cl.def("apply_orientation", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::apply_orientation, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::apply_orientation(const struct handlegraph::handle_t &) --> struct handlegraph::handle_t", pybind11::arg("handle"));
		cl.def("divide_handle", (class std::vector<handlegraph::handle_t> (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, const class std::vector<unsigned long> &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::divide_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::divide_handle(const struct handlegraph::handle_t &, const class std::vector<unsigned long> &) --> class std::vector<handlegraph::handle_t>", pybind11::arg("handle"), pybind11::arg("offsets"));
		cl.def("divide_handle", (struct std::pair<struct handlegraph::handle_t, struct handlegraph::handle_t> (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, unsigned long)) &bdsg::BasePackedGraph<bdsg::STLBackend>::divide_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::divide_handle(const struct handlegraph::handle_t &, unsigned long) --> struct std::pair<struct handlegraph::handle_t, struct handlegraph::handle_t>", pybind11::arg("handle"), pybind11::arg("offset"));
		cl.def("optimize", [](bdsg::BasePackedGraph<bdsg::STLBackend> &o) -> void { return o.optimize(); }, "");
		cl.def("optimize", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(bool)) &bdsg::BasePackedGraph<bdsg::STLBackend>::optimize, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::optimize(bool) --> void", pybind11::arg("allow_id_reassignment"));
		cl.def("apply_ordering", [](bdsg::BasePackedGraph<bdsg::STLBackend> &o, const class std::vector<handlegraph::handle_t> & a0) -> bool { return o.apply_ordering(a0); }, "", pybind11::arg("order"));
		cl.def("apply_ordering", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const class std::vector<handlegraph::handle_t> &, bool)) &bdsg::BasePackedGraph<bdsg::STLBackend>::apply_ordering, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::apply_ordering(const class std::vector<handlegraph::handle_t> &, bool) --> bool", pybind11::arg("order"), pybind11::arg("compact_ids"));
		cl.def("get_path_count", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)() const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_path_count, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_path_count() const --> unsigned long");
		cl.def("has_path", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const std::string &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::has_path, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::has_path(const std::string &) const --> bool", pybind11::arg("path_name"));
		cl.def("get_path_handle", (struct handlegraph::path_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const std::string &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_path_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_path_handle(const std::string &) const --> struct handlegraph::path_handle_t", pybind11::arg("path_name"));
		cl.def("get_path_name", (std::string (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_path_name, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_path_name(const struct handlegraph::path_handle_t &) const --> std::string", pybind11::arg("path_handle"));
		cl.def("get_is_circular", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_is_circular, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_is_circular(const struct handlegraph::path_handle_t &) const --> bool", pybind11::arg("path_handle"));
		cl.def("get_step_count", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_step_count, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_step_count(const struct handlegraph::path_handle_t &) const --> unsigned long", pybind11::arg("path_handle"));
		cl.def("get_step_count", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_step_count, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_step_count(const struct handlegraph::handle_t &) const --> unsigned long", pybind11::arg("handle"));
		cl.def("get_handle_of_step", (struct handlegraph::handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::step_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_handle_of_step, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_handle_of_step(const struct handlegraph::step_handle_t &) const --> struct handlegraph::handle_t", pybind11::arg("step_handle"));
		cl.def("path_begin", (struct handlegraph::step_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::path_begin, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::path_begin(const struct handlegraph::path_handle_t &) const --> struct handlegraph::step_handle_t", pybind11::arg("path_handle"));
		cl.def("path_end", (struct handlegraph::step_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::path_end, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::path_end(const struct handlegraph::path_handle_t &) const --> struct handlegraph::step_handle_t", pybind11::arg("path_handle"));
		cl.def("path_back", (struct handlegraph::step_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::path_back, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::path_back(const struct handlegraph::path_handle_t &) const --> struct handlegraph::step_handle_t", pybind11::arg("path_handle"));
		cl.def("path_front_end", (struct handlegraph::step_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::path_front_end, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::path_front_end(const struct handlegraph::path_handle_t &) const --> struct handlegraph::step_handle_t", pybind11::arg("path_handle"));
		cl.def("has_next_step", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::step_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::has_next_step, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::has_next_step(const struct handlegraph::step_handle_t &) const --> bool", pybind11::arg("step_handle"));
		cl.def("has_previous_step", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::step_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::has_previous_step, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::has_previous_step(const struct handlegraph::step_handle_t &) const --> bool", pybind11::arg("step_handle"));
		cl.def("get_next_step", (struct handlegraph::step_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::step_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_next_step, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_next_step(const struct handlegraph::step_handle_t &) const --> struct handlegraph::step_handle_t", pybind11::arg("step_handle"));
		cl.def("get_previous_step", (struct handlegraph::step_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::step_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_previous_step, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_previous_step(const struct handlegraph::step_handle_t &) const --> struct handlegraph::step_handle_t", pybind11::arg("step_handle"));
		cl.def("get_path_handle_of_step", (struct handlegraph::path_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::step_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_path_handle_of_step, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_path_handle_of_step(const struct handlegraph::step_handle_t &) const --> struct handlegraph::path_handle_t", pybind11::arg("step_handle"));
		cl.def("for_each_path_handle", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const class std::function<bool (const struct handlegraph::path_handle_t &)> &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_path_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_path_handle(const class std::function<bool (const struct handlegraph::path_handle_t &)> &) const --> bool", pybind11::arg("iteratee"));
		cl.def("for_each_step_on_handle", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, const class std::function<bool (const struct handlegraph::step_handle_t &)> &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_step_on_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_step_on_handle(const struct handlegraph::handle_t &, const class std::function<bool (const struct handlegraph::step_handle_t &)> &) const --> bool", pybind11::arg("handle"), pybind11::arg("iteratee"));
		cl.def("steps_of_handle", [](bdsg::BasePackedGraph<bdsg::STLBackend> const &o, const struct handlegraph::handle_t & a0) -> std::vector<handlegraph::step_handle_t> { return o.steps_of_handle(a0); }, "", pybind11::arg("handle"));
		cl.def("steps_of_handle", (class std::vector<handlegraph::step_handle_t> (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, bool) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::steps_of_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::steps_of_handle(const struct handlegraph::handle_t &, bool) const --> class std::vector<handlegraph::step_handle_t>", pybind11::arg("handle"), pybind11::arg("match_orientation"));
		cl.def("is_empty", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::is_empty, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::is_empty(const struct handlegraph::path_handle_t &) const --> bool", pybind11::arg("path_handle"));
		cl.def("destroy_path", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::destroy_path, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::destroy_path(const struct handlegraph::path_handle_t &) --> void", pybind11::arg("path"));
		cl.def("destroy_paths", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const class std::vector<handlegraph::path_handle_t> &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::destroy_paths, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::destroy_paths(const class std::vector<handlegraph::path_handle_t> &) --> void", pybind11::arg("paths"));
		cl.def("create_path_handle", [](bdsg::BasePackedGraph<bdsg::STLBackend> &o, const std::string & a0) -> handlegraph::path_handle_t { return o.create_path_handle(a0); }, "", pybind11::arg("name"));
		cl.def("create_path_handle", (struct handlegraph::path_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const std::string &, bool)) &bdsg::BasePackedGraph<bdsg::STLBackend>::create_path_handle, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::create_path_handle(const std::string &, bool) --> struct handlegraph::path_handle_t", pybind11::arg("name"), pybind11::arg("is_circular"));
		cl.def("append_step", (struct handlegraph::step_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &, const struct handlegraph::handle_t &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::append_step, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::append_step(const struct handlegraph::path_handle_t &, const struct handlegraph::handle_t &) --> struct handlegraph::step_handle_t", pybind11::arg("path"), pybind11::arg("to_append"));
		cl.def("prepend_step", (struct handlegraph::step_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &, const struct handlegraph::handle_t &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::prepend_step, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::prepend_step(const struct handlegraph::path_handle_t &, const struct handlegraph::handle_t &) --> struct handlegraph::step_handle_t", pybind11::arg("path"), pybind11::arg("to_prepend"));
		cl.def("rewrite_segment", (struct std::pair<struct handlegraph::step_handle_t, struct handlegraph::step_handle_t> (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::step_handle_t &, const struct handlegraph::step_handle_t &, const class std::vector<handlegraph::handle_t> &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::rewrite_segment, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::rewrite_segment(const struct handlegraph::step_handle_t &, const struct handlegraph::step_handle_t &, const class std::vector<handlegraph::handle_t> &) --> struct std::pair<struct handlegraph::step_handle_t, struct handlegraph::step_handle_t>", pybind11::arg("segment_begin"), pybind11::arg("segment_end"), pybind11::arg("new_segment"));
		cl.def("set_circularity", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &, bool)) &bdsg::BasePackedGraph<bdsg::STLBackend>::set_circularity, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::set_circularity(const struct handlegraph::path_handle_t &, bool) --> void", pybind11::arg("path"), pybind11::arg("circular"));
		cl.def("set_id_increment", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const long long &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::set_id_increment, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::set_id_increment(const long long &) --> void", pybind11::arg("min_id"));
		cl.def("increment_node_ids", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(long long)) &bdsg::BasePackedGraph<bdsg::STLBackend>::increment_node_ids, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::increment_node_ids(long long) --> void", pybind11::arg("increment"));
		cl.def("reassign_node_ids", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const class std::function<long long (const long long &)> &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::reassign_node_ids, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::reassign_node_ids(const class std::function<long long (const long long &)> &) --> void", pybind11::arg("get_new_id"));
		cl.def("get_sense", (enum handlegraph::PathSense (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_sense, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_sense(const struct handlegraph::path_handle_t &) const --> enum handlegraph::PathSense", pybind11::arg("handle"));
		cl.def("get_sample_name", (std::string (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_sample_name, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_sample_name(const struct handlegraph::path_handle_t &) const --> std::string", pybind11::arg("handle"));
		cl.def("get_locus_name", (std::string (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_locus_name, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_locus_name(const struct handlegraph::path_handle_t &) const --> std::string", pybind11::arg("handle"));
		cl.def("get_haplotype", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_haplotype, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_haplotype(const struct handlegraph::path_handle_t &) const --> unsigned long", pybind11::arg("handle"));
		cl.def("get_phase_block", (unsigned long (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_phase_block, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_phase_block(const struct handlegraph::path_handle_t &) const --> unsigned long", pybind11::arg("handle"));
		cl.def("get_subrange", (struct std::pair<unsigned long, unsigned long> (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::path_handle_t &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_subrange, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_subrange(const struct handlegraph::path_handle_t &) const --> struct std::pair<unsigned long, unsigned long>", pybind11::arg("handle"));
		cl.def("create_path", [](bdsg::BasePackedGraph<bdsg::STLBackend> &o, const enum handlegraph::PathSense & a0, const std::string & a1, const std::string & a2, const unsigned long & a3, const unsigned long & a4, const struct std::pair<unsigned long, unsigned long> & a5) -> handlegraph::path_handle_t { return o.create_path(a0, a1, a2, a3, a4, a5); }, "", pybind11::arg("sense"), pybind11::arg("sample"), pybind11::arg("locus"), pybind11::arg("haplotype"), pybind11::arg("phase_block"), pybind11::arg("subrange"));
		cl.def("create_path", (struct handlegraph::path_handle_t (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const enum handlegraph::PathSense &, const std::string &, const std::string &, const unsigned long &, const unsigned long &, const struct std::pair<unsigned long, unsigned long> &, bool)) &bdsg::BasePackedGraph<bdsg::STLBackend>::create_path, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::create_path(const enum handlegraph::PathSense &, const std::string &, const std::string &, const unsigned long &, const unsigned long &, const struct std::pair<unsigned long, unsigned long> &, bool) --> struct handlegraph::path_handle_t", pybind11::arg("sense"), pybind11::arg("sample"), pybind11::arg("locus"), pybind11::arg("haplotype"), pybind11::arg("phase_block"), pybind11::arg("subrange"), pybind11::arg("is_circular"));
		cl.def("for_each_step_of_sense", (bool (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const struct handlegraph::handle_t &, const enum handlegraph::PathSense &, const class std::function<bool (const struct handlegraph::step_handle_t &)> &) const) &bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_step_of_sense, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_step_of_sense(const struct handlegraph::handle_t &, const enum handlegraph::PathSense &, const class std::function<bool (const struct handlegraph::step_handle_t &)> &) const --> bool", pybind11::arg("visited"), pybind11::arg("sense"), pybind11::arg("iteratee"));
		cl.def("get_magic_number", (unsigned int (bdsg::BasePackedGraph<bdsg::STLBackend>::*)() const) &bdsg::BasePackedGraph<bdsg::STLBackend>::get_magic_number, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::get_magic_number() const --> unsigned int");
		cl.def("deserialize", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const std::string &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::deserialize, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::deserialize(const std::string &) --> void", pybind11::arg("filename"));
		cl.def("serialize", (void (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const std::string &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::serialize, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::serialize(const std::string &) --> void", pybind11::arg("filename"));
		cl.def("assign", (class bdsg::BasePackedGraph<struct bdsg::STLBackend> & (bdsg::BasePackedGraph<bdsg::STLBackend>::*)(const class bdsg::BasePackedGraph<struct bdsg::STLBackend> &)) &bdsg::BasePackedGraph<bdsg::STLBackend>::operator=, "C++: bdsg::BasePackedGraph<bdsg::STLBackend>::operator=(const class bdsg::BasePackedGraph<struct bdsg::STLBackend> &) --> class bdsg::BasePackedGraph<struct bdsg::STLBackend> &", pybind11::return_value_policy::automatic, pybind11::arg(""));
	}
}
